app/__init__.py
from flask import Flask

import logging
from app.config import DevelopmentConfig
from app.routes.api import api_bp
from app.routes.frontend import frontend_bp
from app.errors import errors as errors_bp


def create_app(config_class=DevelopmentConfig):
    """
    Creates the Flask app and utilizes the routes & errors blueprints.
    :return: Returns the Flask application
    """
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.register_blueprint(api_bp)
    app.register_blueprint(frontend_bp)
    app.register_blueprint(errors_bp)

    logging.basicConfig(
        level=app.config['LOG_LEVEL'],
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(app.config['LOG_FILE'])
        ]
    )
    app.logger.setLevel(app.config['LOG_LEVEL'])

    return app

app/routes/api.py
from flask import Blueprint, jsonify, current_app
from app.services import get_all_packages, get_package_details

api_bp = Blueprint('api', __name__, url_prefix='/api')


@api_bp.route('/packages', methods=['GET'])
def get_pkgs():
    try:
        packages = get_all_packages()
        return jsonify(packages)
    except Exception as e:
        current_app.logger.error(f"Error getting packages: {str(e)}")
        return jsonify({"error": "Internal Server Error", "message": str(e)}), 500


@api_bp.route('/packages/<string:package_name>', methods=['GET'])
def get_pkg_details(package_name):
    try:
        package = get_package_details(package_name)
        if not package:
            return jsonify({"error": "Not Found", "message": "Package not found"}), 404
        return jsonify(package)
    except Exception as e:
        current_app.logger.error(f"Error getting package details for {package_name}: {str(e)}")
        return jsonify({"error": "Internal Server Error", "message": str(e)}), 500

app/routes/frontend.py
from flask import Blueprint, render_template, current_app
from app.services import get_all_packages, get_package_details

frontend_bp = Blueprint('frontend', __name__)

@frontend_bp.route('/')
def index():
    try:
        packages = get_all_packages()
        return render_template('index.html', packages=packages)
    except Exception as e:
        current_app.logger.error(f"Error getting packages: {str(e)}")
        return render_template('index.html', packages=[])


@frontend_bp.route('/packages/<string:package_name>')
def package_details(package_name):
    try:
        package = get_package_details(package_name)
        if not package:
            current_app.logger.warning(f"Package not found: {package_name}")
            return render_template('package_details.html', package=None)
        return render_template('package_details.html', package=package)
    except Exception as e:
        current_app.logger.error(f"error getting package details for {package_name}: {str(e)}")
        return render_template('package_details.html', package=None)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Package Viewer</title>
</head>
<body>
<header>
    <h1>System Package Viewer</h1>
</header>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h2>Available Packages</h2>
    <ul>
        {% for package in packages %}
            <li>
                <a href="{{ url_for('frontend.package_details', package_name=package.name) }}">{{ package.name }}
                    - {{ package.version }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/package_details.html
{% extends "base.html" %}

{% block content %}
    {% if package %}
        <h2>Package Details: {{ package.name }}</h2>
        <p><strong>Description:</strong> {{ package.description }}</p>
        <p><strong>Dependencies:</strong></p>
        <ul>
            {% for alt_group in package.dependencies %}
                <li>
                    {% for dep in alt_group %}
                        {{ dep.name }}{{ dep.version }}{% if dep.url %} (
                        <a href="{{ url_for('frontend.package_details', package_name=dep.name) }}">Details</a>)
                    {% endif %}
                        {% if not loop.last %}|{% endif %}
                    {% endfor %}
                </li>
            {% endfor %}
        </ul>
        <p><strong>Reverse Dependencies:</strong></p>
        <ul>
            {% for rev_dep in package.reverse_dependencies %}
                <li>
                    <a href="{{ url_for('frontend.package_details', package_name=rev_dep.name) }}">{{ rev_dep.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Package not found</h2>
        <p>The package you are looking for does not exist.</p>
    {% endif %}
{% endblock %}